export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-RouteChi-Cache",
  cacheHit: "X-RouteChi-Cache-Hit",
  compression: "X-RouteChi-Compression",
  costSaved: "X-RouteChi-Cost-Saved",
  fallbackAttempts: "X-RouteChi-Fallback-Attempts",
  latencyMs: "X-RouteChi-Latency-Ms",
  model: "X-RouteChi-Model",
  progress: "X-RouteChi-Progress",
  provider: "X-RouteChi-Provider",
  requestId: "X-RouteChi-Request-Id",
  responseCost: "X-RouteChi-Response-Cost",
  tokensIn: "X-RouteChi-Tokens-In",
  tokensOut: "X-RouteChi-Tokens-Out",
  version: "X-RouteChi-Version",
} as const;
